export const styles = {
  container: {
    minHeight: '100vh',
    background: '#f8f9fb',
    fontFamily: "'Inter', sans-serif",
  },
  // Header Section
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    padding: '28px 32px 0',
  },
  headerLeft: {},
  headerTitle: {
    fontSize: '24px',
    fontWeight: 900,
    color: '#0f172a',
    letterSpacing: '-0.5px',
    lineHeight: 1.2,
    margin: 0,
  },
  headerSubtitle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '3px',
    textTransform: 'uppercase',
    color: '#94a3b8',
    marginTop: '4px',
  },
  // Search
  searchContainer: {
    position: 'relative',
  },
  searchIcon: {
    position: 'absolute',
    left: '14px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
  },
  searchInput: {
    padding: '10px 16px 10px 40px',
    border: '1.5px solid #e2e8f0',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: 500,
    color: '#334155',
    background: '#ffffff',
    width: '320px',
    outline: 'none',
    transition: 'border-color 0.2s, box-shadow 0.2s',
    fontFamily: "'Inter', sans-serif",
  },
  // Pipeline Tabs
  pipelineTabs: {
    display: 'flex',
    alignItems: 'center',
    gap: '0',
    margin: '24px 32px 24px',
    background: '#ffffff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
  },
  pipelineTab: (isActive) => ({
    flex: 1,
    padding: '14px 24px',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.8px',
    textTransform: 'uppercase',
    color: isActive ? '#f97316' : '#94a3b8',
    background: isActive ? '#fff' : '#fafbfc',
    border: 'none',
    borderBottom: isActive ? '3px solid #f97316' : '3px solid transparent',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontFamily: "'Inter', sans-serif",
    position: 'relative',
  }),
  // Table
  tableContainer: {
    margin: '0 32px 32px',
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  tableHead: {
    background: '#f8fafc',
    borderBottom: '1px solid #e2e8f0',
  },
  th: {
    padding: '14px 20px',
    fontSize: '10px',
    fontWeight: 800,
    letterSpacing: '1.2px',
    textTransform: 'uppercase',
    color: '#64748b',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  tr: (isHovered) => ({
    borderBottom: '1px solid #f1f5f9',
    transition: 'background 0.15s ease',
    background: isHovered ? '#fafbfe' : 'transparent',
    cursor: 'pointer',
  }),
  td: {
    padding: '16px 20px',
    verticalAlign: 'middle',
  },
  // Farmer Cell
  farmerCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    minWidth: '200px',
  },
  avatar: (bgColor) => ({
    width: '42px',
    height: '42px',
    borderRadius: '50%',
    background: bgColor,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 700,
    fontSize: '15px',
    flexShrink: 0,
    boxShadow: `0 2px 8px ${bgColor}40`,
  }),
  farmerInfo: {},
  farmerName: {
    fontSize: '13.5px',
    fontWeight: 700,
    color: '#1e40af',
    lineHeight: 1.3,
    cursor: 'pointer',
  },
  farmerId: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#f97316',
    marginTop: '1px',
  },
  farmerPhone: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    color: '#94a3b8',
    marginTop: '2px',
  },
  // Address Cell
  addressMain: {
    fontSize: '13.5px',
    fontWeight: 600,
    color: '#1e293b',
    lineHeight: 1.4,
  },
  addressSub: {
    fontSize: '11.5px',
    color: '#94a3b8',
    fontWeight: 500,
    marginTop: '2px',
  },
  // Unit Profile
  unitProfile: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#334155',
    whiteSpace: 'nowrap',
  },
  // Executive
  executiveName: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  // Start Verify Button
  verifyBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 20px',
    background: 'linear-gradient(135deg, #f97316, #ea580c)',
    border: 'none',
    borderRadius: '8px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#fff',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    letterSpacing: '0.8px',
    textTransform: 'uppercase',
    boxShadow: '0 2px 8px rgba(249, 115, 22, 0.35)',
    whiteSpace: 'nowrap',
    fontFamily: "'Inter', sans-serif",
  },
  // Inbound Signal Pill
  inboundPill: {
    position: 'fixed',
    bottom: '24px',
    right: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 20px',
    background: 'linear-gradient(135deg, #f97316, #ea580c)',
    borderRadius: '50px',
    color: '#fff',
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.5px',
    boxShadow: '0 4px 20px rgba(249, 115, 22, 0.4)',
    cursor: 'pointer',
    zIndex: 100,
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    textTransform: 'uppercase',
    fontFamily: "'Inter', sans-serif",
  },
  // Loading & Empty
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '80px 0',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    color: '#94a3b8',
    fontSize: '14px',
    fontWeight: 500,
  },
  // Pagination
  pagination: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderTop: '1px solid #f1f5f9',
  },
  pageBtn: (disabled) => ({
    padding: '6px',
    background: 'none',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    cursor: disabled ? 'not-allowed' : 'pointer',
    opacity: disabled ? 0.4 : 1,
    color: '#475569',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s',
  }),
  pageNum: (isActive) => ({
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: isActive ? 700 : 500,
    color: isActive ? '#fff' : '#475569',
    background: isActive ? '#f97316' : 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontFamily: "'Inter', sans-serif",
  }),
};